intentparser:
  llm_api_key: "YOUR_LLM_API_KEY"
  model: "gpt-4"

fs: {}

mcp:
  orchestrator:
    timeout_seconds: 30

logging:
  level: "info"
  file: "~/.marco/logs/marco.log"

cache:
  assignments_ttl_minutes: 10
